import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./style/globals.css"
import Provider from "@/provider/provider"
import SheetProvider from "@/provider/sheet-provider"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <Provider>
      <html lang="en">
        <body className={inter.className}>
          <SheetProvider />
          {children}
        </body>
      </html>
    </Provider>
  )
}
